FROM tomcat:8-jre8

MAINTAINER H.S.

ENV GITBUCKET_HOME /var/gitbucket

RUN rm -rf /usr/local/tomcat/webapps/ROOT

ADD https://github.com/gitbucket/gitbucket/releases/download/4.5/gitbucket.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080 29418

CMD [ "/usr/local/tomcat/bin/catalina.sh", "run" ]
